### ISSUE TITLE
Support ES6 style templates

### ISSUE THREAD

**Issue by prayerslayer** [floatdrop/plugin-jsx#3]
As described [here](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html).

**Comment by floatdrop** [comment]
Merged in `beta` branch. Usage:

`jspm install jsx@beta`

**Comment by asaf** [comment]
@floatdrop Beta is broken? i'm getting errors for any file I try to import.

**Comment by floatdrop** [comment]
@asaf use latest version (`1.1.0`) - it have `react@^0.13` as dependency now.

**Comment by asaf** [comment]
@floatdrop Thanks, tried with `1.1.0`, I fail to use property initializers as described here (http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html),

Should it be supported by this plugin?

**Comment by floatdrop** [comment]
@asaf dunno, they could drop this feature on release. I recommend to use babel, because of react-tools deprecation: http://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

**Comment by asaf** [comment]
@floatdrop Thanks, this plugin supports Babel ? I see that it uses jstransform which uses react tools........

**Comment by floatdrop** [comment]
@asaf jspm can automatically use babel transpiler without external plugins - here is related issue https://github.com/jspm/jspm-cli/issues/566

**Comment by asaf** [comment]
@floatdrop Awesome, thanks!
